//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldChooser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FieldChooser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C0 or C1 control code.
        /// </summary>
        internal static string Cc {
            get {
                return ResourceManager.GetString("Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format control character.
        /// </summary>
        internal static string Cf {
            get {
                return ResourceManager.GetString("Cf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unassigned character.
        /// </summary>
        internal static string Cn {
            get {
                return ResourceManager.GetString("Cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private use character.
        /// </summary>
        internal static string Co {
            get {
                return ResourceManager.GetString("Co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suragate code point.
        /// </summary>
        internal static string Cs {
            get {
                return ResourceManager.GetString("Cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Dots {
            get {
                object obj = ResourceManager.GetObject("Dots", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DotsDisabled {
            get {
                object obj = ResourceManager.GetObject("DotsDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lowercase letter.
        /// </summary>
        internal static string Ll {
            get {
                return ResourceManager.GetString("Ll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modifier letter.
        /// </summary>
        internal static string Lm {
            get {
                return ResourceManager.GetString("Lm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other letters, including syllables and ideographs.
        /// </summary>
        internal static string Lo {
            get {
                return ResourceManager.GetString("Lo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digraphic character, with first part uppercase.
        /// </summary>
        internal static string Lt {
            get {
                return ResourceManager.GetString("Lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uppercase letter.
        /// </summary>
        internal static string Lu {
            get {
                return ResourceManager.GetString("Lu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spacing combining mark.
        /// </summary>
        internal static string Mc {
            get {
                return ResourceManager.GetString("Mc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enclosing combining mark.
        /// </summary>
        internal static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Menu_16x {
            get {
                object obj = ResourceManager.GetObject("Menu_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Fields....
        /// </summary>
        internal static string menu_text {
            get {
                return ResourceManager.GetString("menu_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nonspacing combining mark.
        /// </summary>
        internal static string Mn {
            get {
                return ResourceManager.GetString("Mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decimal digit.
        /// </summary>
        internal static string Nd {
            get {
                return ResourceManager.GetString("Nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to letter like numeric character.
        /// </summary>
        internal static string Nl {
            get {
                return ResourceManager.GetString("Nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numeric character.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to punctuation mark.
        /// </summary>
        internal static string Pc {
            get {
                return ResourceManager.GetString("Pc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dash or hyphen punctuation mark.
        /// </summary>
        internal static string Pd {
            get {
                return ResourceManager.GetString("Pd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to closing punctuation mark.
        /// </summary>
        internal static string Pe {
            get {
                return ResourceManager.GetString("Pe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to final quotation mark.
        /// </summary>
        internal static string Pf {
            get {
                return ResourceManager.GetString("Pf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initial quotation mark.
        /// </summary>
        internal static string Pi {
            get {
                return ResourceManager.GetString("Pi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to punctuation mark.
        /// </summary>
        internal static string Po {
            get {
                return ResourceManager.GetString("Po", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to opening punctuation mark.
        /// </summary>
        internal static string Ps {
            get {
                return ResourceManager.GetString("Ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to currency symbol.
        /// </summary>
        internal static string Sc {
            get {
                return ResourceManager.GetString("Sc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to non-letterlike modifier symbol.
        /// </summary>
        internal static string Sk {
            get {
                return ResourceManager.GetString("Sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mathematical symbol.
        /// </summary>
        internal static string Sm {
            get {
                return ResourceManager.GetString("Sm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to symbol.
        /// </summary>
        internal static string So {
            get {
                return ResourceManager.GetString("So", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line seperator.
        /// </summary>
        internal static string Zl {
            get {
                return ResourceManager.GetString("Zl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to paragraph seperator.
        /// </summary>
        internal static string Zp {
            get {
                return ResourceManager.GetString("Zp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to space character.
        /// </summary>
        internal static string Zs {
            get {
                return ResourceManager.GetString("Zs", resourceCulture);
            }
        }
    }
}
